import Head from 'next/head'
import styles from './MainLayout.module.css'


import { Navbar } from '../Navbar';

type Props = {
    children: React.ReactNode; // 👈️ added type for children
};
  

export const MainLayout = ( props: Props ) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <Navbar/>

                { props.children }

                <div className={styles.description}>
                    <p>
                        Get started by editing&nbsp;
                        <code className={styles.code}>pages/home.tsx</code>
                    </p>
                </div>

            </main>
        </>
    )
}
